"""empty message

Revision ID: 37db834d6bb8
Revises: 9f473f701fdb
Create Date: 2024-11-25 15:49:37.522989

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37db834d6bb8'
down_revision = '9f473f701fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Groups')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('group_number', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('profession_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('collage_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
