"""empty message

Revision ID: 435799f43713
Revises: 0ab21631b71d
Create Date: 2024-11-19 15:23:08.312605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '435799f43713'
down_revision = '0ab21631b71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('profession_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('college_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('college_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('profession_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)

    # ### end Alembic commands ###
