"""empty message

Revision ID: 69808bdae0a9
Revises: 4f8cd0cbeb8c
Create Date: 2024-11-21 16:03:45.928466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69808bdae0a9'
down_revision = '4f8cd0cbeb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
