"""empty message

Revision ID: 8770f6e2e616
Revises: b51e2149fa27
Create Date: 2024-12-03 13:07:44.386490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8770f6e2e616'
down_revision = 'b51e2149fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colleges', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=18),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
