"""empty message

Revision ID: 8f65f3f7a882
Revises: 8770f6e2e616
Create Date: 2024-12-04 12:39:04.230164

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f65f3f7a882'
down_revision = '8770f6e2e616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('profession_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('college_id',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('college_id',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)
        batch_op.alter_column('profession_id',
               existing_type=sa.String(length=255),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
