"""empty message

Revision ID: 9f473f701fdb
Revises: d18c044b3fad
Create Date: 2024-11-25 15:47:14.273458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f473f701fdb'
down_revision = 'd18c044b3fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
