"""empty message

Revision ID: b51e2149fa27
Revises: ce4bc489b5f7
Create Date: 2024-12-02 13:06:27.366150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51e2149fa27'
down_revision = 'ce4bc489b5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_unique_constraint('_teacher_uc', ['name', 'email', 'phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint('_teacher_uc', type_='unique')

    # ### end Alembic commands ###
