"""empty message

Revision ID: c67022786c47
Revises: 
Create Date: 2024-12-10 18:03:04.992803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67022786c47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_profession',
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('profession_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'profession_id')
    )
    op.create_table('teacher_college',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('college_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'college_id')
    )
    op.create_table('teacher_module',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'module_id')
    )
    op.create_table('students',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('teacher_module')
    op.drop_table('teacher_college')
    op.drop_table('module_profession')
    op.drop_table('groups')
    op.drop_table('college_profession')
    op.drop_table('teachers')
    op.drop_table('professions')
    op.drop_table('modules')
    op.drop_table('colleges')
    # ### end Alembic commands ###
