"""empty message

Revision ID: ce4bc489b5f7
Revises: 37db834d6bb8
Create Date: 2024-12-02 12:30:33.056998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce4bc489b5f7'
down_revision = '37db834d6bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.BIGINT(display_width=20),
               type_=sa.String(length=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=18),
               type_=mysql.BIGINT(display_width=20),
               existing_nullable=False)

    # ### end Alembic commands ###
