"""empty message

Revision ID: d34f0e287d5b
Revises: aa04f2cccc86
Create Date: 2024-11-18 15:40:41.791525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34f0e287d5b'
down_revision = 'aa04f2cccc86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('group_number', sa.BigInteger(), nullable=False),
    sa.Column('profession_id', sa.BigInteger(), nullable=False),
    sa.Column('collage_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Groups')
    # ### end Alembic commands ###
