"""empty message

Revision ID: f04c6da56581
Revises: 3644aa5e4aab
Create Date: 2024-11-15 15:31:40.906727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04c6da56581'
down_revision = '3644aa5e4aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_profession',
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('profession_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.ForeignKeyConstraint(['profession_id'], ['professions.id'], ),
    sa.PrimaryKeyConstraint('module_id', 'profession_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_profession')
    # ### end Alembic commands ###
