"""empty message

Revision ID: f2ca63b56058
Revises: 06e827e2c2ef
Create Date: 2024-11-18 16:19:47.501889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2ca63b56058'
down_revision = '06e827e2c2ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('profession_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.alter_column('collage_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=True)
        batch_op.create_foreign_key(None, 'colleges', ['collage_id'], ['id'])
        batch_op.create_foreign_key(None, 'professions', ['profession_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('collage_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)
        batch_op.alter_column('profession_id',
               existing_type=mysql.BIGINT(display_width=20),
               nullable=False)

    # ### end Alembic commands ###
